### ISSUE TITLE
Animated: `useNativeDriver` was not specified

### ISSUE THREAD

**Issue by el2e10** [wangdicoder/react-native-indicator#14]
Getting a warning saying Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

**Comment by djschilling** [comment]
I' also getting this warning:
![Simulator Screen Shot - iPhone 11 - 2020-05-06 at 14 59 56](https://user-images.githubusercontent.com/3503166/81179751-5e729000-8faa-11ea-812b-8cb18f5a7497.png)

I get it when using `DotsLoader`

**Comment by el2e10** [comment]
In node_modules/react-native-indicator/lib/loader/DotsLoader.js add `useNativeDriver:false` in `Animate.timing` like:
`  _animation = () => {
    function seq(self, i) {
      return Animated.sequence([
        Animated.timing(self.state.scales[i], {
          toValue: 1,
          duration: 300,
          delay: (i + 1) * 200,
          useNativeDriver:false
        }),
        Animated.timing(self.state.scales[i], {
          toValue: 0,
          duration: 300,
          delay: 50,
          useNativeDriver:false
        }),
      ]);
    }`

**Comment by usamaabutt** [comment]
I am also facing the same warning is it harmful for the app ? How can i fix this?
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-18 at 15 27 32](https://user-images.githubusercontent.com/44516486/87850630-3a68ee80-c90b-11ea-91b6-630ccf4d9921.png)

**Comment by wangdicoder** [comment]
fixed in v1.2.2
