### ISSUE TITLE
Consult a question on the InteractionManager

### ISSUE THREAD

**Issue by xuanheScript** [wangdicoder/react-native-indicator#2]
First of all, your component is really good, but I encountered a problem, I am waiting for the fetch to display the animation, in order to optimize the performance of the request after the implementation of the method written in the InteractionManager.runAfterInteractions (callback), but your animation components Has been in the implementation of the runAfterInteractions incident can not be triggered. Is there a good suggestion?

**Comment by wangdicoder** [comment]
@xuanheScript Hi, I am a little bit confused what you want to express. I understand that you said you hope to do some things in the callback function of "InteractionManager.runAfterInteractions". However, I don't know the next sentence. Do you want to say this animation component should also put into the callback function of runAfterInteractions? 

BTW, I understand Chinese, so you could speak Chinese to express more clearly your thought.

**Comment by xuanheScript** [comment]
是这样的，当我push到一个新的route时，我需要请求一些数据，并且在Navigator跳转的动画完成后去执行所以使用InteractionManager.runAfterInteractions在动画结束后去渲染界面，但是在这等待的期间，我需要一个loading的效果，所以我使用你的优秀组件，但是因为你的组件是无限循环的动画，所以InteractionManager.runAfterInteractions永远不会被触发。现在你理解我的意思了吗？只是请教有没有适合的处理方法 @wangdicoder
