### ISSUE TITLE
How can we pass in color to change the color of the animation from blue to some other color ?

### ISSUE THREAD

**Issue by PManager1** [wangdicoder/react-native-indicator#3]
<View style="loadView">
              <CirclesLoader color:red />
              <TextLoader text="Loading" />
            </View>

**Comment by rjacobskind** [comment]
try changing your color prop to 'color={'red'}

**Comment by Zhang** [comment]
Having a similar problem, when changing my colors to another hex does't work
`<DotsLoader color={'#f6f8fa'} />`

Strangely, per @rjacobskind comment, changing it to
`<DotsLoader color={'red'} />`
works

**Comment by wangdicoder** [comment]
Hi, trying to remove the bracket in the color attribute will be ok. eg.
`<DotsLoader color="#f6f8fa"/>`
`<DotsLoader color="green"/>`
