### ISSUE TITLE
引入react-native-loader后，项目启动报错，RN版本0.49.3.

### ISSUE THREAD

**Issue by happyliuzh** [wangdicoder/react-native-indicator#4]
![image](https://user-images.githubusercontent.com/10329041/31774032-2d52b14a-b4aa-11e7-9ace-d826da7016b0.png)

**Comment by rahulnakate** [comment]
I am facing same Issue . If anybody get solution Please let me know

**Comment by aamping** [comment]
I submitted a PR to fix this issue:  https://github.com/wangdicoder/react-native-indicator/pull/5

**Comment by wangdicoder** [comment]
Thanks, @aamping, I have merged your PR.
